# provide a name if you wish
# name: btlz-test

networks:
  postgres-net:
    driver: bridge

volumes:
  postgres-vol:
    driver: local

services:

  postgres:
    container_name: postgres

    image: postgres:16.1-alpine

    env_file: "./.env"

    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - postgres-vol:/var/lib/postgresql/data

    networks:
      - postgres-net

    expose:
      - ${POSTGRES_PORT}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


  app:
    container_name: app

    build:
      context: .
      dockerfile: Dockerfile

    env_file: "./.env"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${APP_PORT}
      NODE_ENV: production
      WB_HEADER_API_KEY: ${WB_HEADER_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      UPDATE_DB_MASK: ${UPDATE_DB_MASK}
      UPDATE_TABLES_MASK: ${UPDATE_TABLES_MASK}
      SHEETS: ${SHEETS}

    ports:
      - ${APP_PORT}:${APP_PORT}

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    command: [ "npm", "run", "start" ]
    restart: unless-stopped
